package com.example.budgettracker

import java.util.Calendar


/**
 * @param id ID of financial object. Autogenerated on creation.
 * @param type type of financial object. can be Savings, Wallet, Debts, Borrowed.
 * @param name name of financial object.
 * @param description description of financial object.
 * @param targetAmount target amount of financial object. Defaults to 0.0
 * @param level determines if a financial object is parent or child. defaults to parent.
 * @param valueAmount total of all transaction amount within the financial object.
 * @param dateCreated creation date of Financial Object. Autogenerated on creation.
 * by the Financial Objects Relation Table.
 */
data class FinancialObjectModel(
    var id: String = IntegerTools.generateRandom(Constants.FINANCIAL_OBJECT_ID_LENGHT).toString(),
    var type: String,
    var name: String,
    var description: String,
    var targetAmount: Double = 0.0,
    var level: String = Const.LEVEL_PARENT,
    var valueAmount: Double = 0.0,
    var dateCreated: Calendar = Calendar.getInstance()
)

